name: "Leetcode Sync"
description: "Automatically parse and download recent LeetCode submissions into a GitHub repository"
branding:
  icon: git-commit
  color: green

inputs:
  GITHUB_TOKEN:
    description: "GitHub Token"
    required: true
  LEETCODE_SESSION:
    description: "LeetCode Session"
    required: true
  LEETCODE_CSRF_TOKEN:
    description: "LeetCode CSRF Token"
    required: true

runs:
  using: "composite"
  steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.action_path }}/requirements.txt

      - name: Execute py script
        shell: bash
        run: python ${{ github.action_path }}/main.py
        env:
          LEETCODE_SESSION: ${{ inputs.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ inputs.LEETCODE_CSRF_TOKEN }}

      - name: Commit files
        shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -a -m "[Leetcode Sync] Add changed"
          
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ inputs.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
